// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/create-family" | "/family-space" | "/family-space/data-capture" | "/family-space/members/[personId]" | "/family-space/requests" | "/join-family" | "/platform/admin/data-capture" | "/platform/admin/security" | "/platform/auth" | "/tenant/workspace" | "/tenant/workspace/members/[personId]"
type AppRouteHandlerRoutes = "/api/auth/active-workspace" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/register-admin" | "/api/auth/register-user" | "/api/auth/resend-otp" | "/api/auth/send-otp" | "/api/auth/verify-otp" | "/api/families" | "/api/families/[id]/audit-logs" | "/api/families/[id]/join-requests" | "/api/families/[id]/join-requests/[requestId]/review" | "/api/families/[id]/member-logins" | "/api/families/[id]/member-logins/[membershipId]" | "/api/families/[id]/people" | "/api/families/[id]/people/[personId]" | "/api/families/[id]/person-merges/[auditLogId]/undo" | "/api/families/[id]/relationships" | "/api/families/[id]/relationships/[relationshipId]" | "/api/join-requests"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/active-workspace": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/register-admin": {}
  "/api/auth/register-user": {}
  "/api/auth/resend-otp": {}
  "/api/auth/send-otp": {}
  "/api/auth/verify-otp": {}
  "/api/families": {}
  "/api/families/[id]/audit-logs": { "id": string; }
  "/api/families/[id]/join-requests": { "id": string; }
  "/api/families/[id]/join-requests/[requestId]/review": { "id": string; "requestId": string; }
  "/api/families/[id]/member-logins": { "id": string; }
  "/api/families/[id]/member-logins/[membershipId]": { "id": string; "membershipId": string; }
  "/api/families/[id]/people": { "id": string; }
  "/api/families/[id]/people/[personId]": { "id": string; "personId": string; }
  "/api/families/[id]/person-merges/[auditLogId]/undo": { "id": string; "auditLogId": string; }
  "/api/families/[id]/relationships": { "id": string; }
  "/api/families/[id]/relationships/[relationshipId]": { "id": string; "relationshipId": string; }
  "/api/join-requests": {}
  "/create-family": {}
  "/family-space": {}
  "/family-space/data-capture": {}
  "/family-space/members/[personId]": { "personId": string; }
  "/family-space/requests": {}
  "/join-family": {}
  "/platform/admin/data-capture": {}
  "/platform/admin/security": {}
  "/platform/auth": {}
  "/tenant/workspace": {}
  "/tenant/workspace/members/[personId]": { "personId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
