// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/create-family/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create-family">> = Specific
  const handler = {} as typeof import("../../app/create-family/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/family-space/data-capture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/family-space/data-capture">> = Specific
  const handler = {} as typeof import("../../app/family-space/data-capture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/family-space/members/[personId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/family-space/members/[personId]">> = Specific
  const handler = {} as typeof import("../../app/family-space/members/[personId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/family-space/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/family-space">> = Specific
  const handler = {} as typeof import("../../app/family-space/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/family-space/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/family-space/requests">> = Specific
  const handler = {} as typeof import("../../app/family-space/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/join-family/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/join-family">> = Specific
  const handler = {} as typeof import("../../app/join-family/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform/admin/data-capture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/admin/data-capture">> = Specific
  const handler = {} as typeof import("../../app/platform/admin/data-capture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform/admin/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/admin/security">> = Specific
  const handler = {} as typeof import("../../app/platform/admin/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/auth">> = Specific
  const handler = {} as typeof import("../../app/platform/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tenant/workspace/members/[personId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tenant/workspace/members/[personId]">> = Specific
  const handler = {} as typeof import("../../app/tenant/workspace/members/[personId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tenant/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tenant/workspace">> = Specific
  const handler = {} as typeof import("../../app/tenant/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/active-workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/active-workspace">> = Specific
  const handler = {} as typeof import("../../app/api/auth/active-workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/register-admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register-admin">> = Specific
  const handler = {} as typeof import("../../app/api/auth/register-admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/register-user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register-user">> = Specific
  const handler = {} as typeof import("../../app/api/auth/register-user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/resend-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/resend-otp">> = Specific
  const handler = {} as typeof import("../../app/api/auth/resend-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/send-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/send-otp">> = Specific
  const handler = {} as typeof import("../../app/api/auth/send-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/verify-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-otp">> = Specific
  const handler = {} as typeof import("../../app/api/auth/verify-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/families/[id]/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/[id]/audit-logs">> = Specific
  const handler = {} as typeof import("../../app/api/families/[id]/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/families/[id]/join-requests/[requestId]/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/[id]/join-requests/[requestId]/review">> = Specific
  const handler = {} as typeof import("../../app/api/families/[id]/join-requests/[requestId]/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/families/[id]/join-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/[id]/join-requests">> = Specific
  const handler = {} as typeof import("../../app/api/families/[id]/join-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/families/[id]/member-logins/[membershipId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/[id]/member-logins/[membershipId]">> = Specific
  const handler = {} as typeof import("../../app/api/families/[id]/member-logins/[membershipId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/families/[id]/member-logins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/[id]/member-logins">> = Specific
  const handler = {} as typeof import("../../app/api/families/[id]/member-logins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/families/[id]/people/[personId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/[id]/people/[personId]">> = Specific
  const handler = {} as typeof import("../../app/api/families/[id]/people/[personId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/families/[id]/people/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/[id]/people">> = Specific
  const handler = {} as typeof import("../../app/api/families/[id]/people/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/families/[id]/person-merges/[auditLogId]/undo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/[id]/person-merges/[auditLogId]/undo">> = Specific
  const handler = {} as typeof import("../../app/api/families/[id]/person-merges/[auditLogId]/undo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/families/[id]/relationships/[relationshipId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/[id]/relationships/[relationshipId]">> = Specific
  const handler = {} as typeof import("../../app/api/families/[id]/relationships/[relationshipId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/families/[id]/relationships/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/[id]/relationships">> = Specific
  const handler = {} as typeof import("../../app/api/families/[id]/relationships/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/families/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families">> = Specific
  const handler = {} as typeof import("../../app/api/families/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/join-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/join-requests">> = Specific
  const handler = {} as typeof import("../../app/api/join-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
